unique_ids:
  assets:
    standard-page.html: FWNBRYTQ5FYKRMFR5TQCDTKGH36EROKJ
    theme.css: 4XELZEEUTVXOLQDXMJPQ3IRQPNKSRQ3I
  forms:
    Form1: 6LHPGAY352WAAF56DS4UD744L2O457UK
  modules: {}
  scripts: {}
  server_modules: {}
